field.widget.settings.commerce_entity_select:
  type: mapping
  label: 'Entity select widget settings'
  mapping:
    autocomplete_threshold:
      type: integer
      label: 'Autocomplete threshold'
    autocomplete_size:
      type: integer
      label: 'Autocomplete size'
    autocomplete_placeholder:
      type: string
      label: 'Autocomplete placeholder'

views.argument_validator.commerce_current_user:
  type: mapping
  label: 'Current user'
  mapping:
    restrict_roles:
      type: boolean
      label: 'Restrict user based on role, if the user doesn''t match the current user.'
    roles:
      type: sequence
      label: 'Restrict to the selected roles'
      sequence:
        type: string
        label: 'Role'

views.field.commerce_entity_bundle:
  type: views.field.field
  mapping:
    hide_single_bundle:
      type: boolean
      label: 'Hide if there''s only one bundle.'

views.filter.commerce_entity_bundle:
  type: views.filter.in_operator
  label: 'Bundle'
  mapping:
    expose:
      type: mapping
      label: 'Expose'
      mapping:
        reduce:
          type: boolean
          label: 'Reduce'
        hide_single_bundle:
          type: boolean
          label: 'Hide if there''s only one bundle.'
