commerce_order.commerce_order_type.*.third_party.commerce_cart:
  type: mapping
  label: 'Shopping cart refresh settings'
  mapping:
    refresh_mode:
        type: string
        label: 'Shopping cart refresh mode'
    refresh_frequency:
        type: integer
        label: 'Shopping cart refresh frequency'

commerce_cart.settings:
  type: config_object
  label: 'Commerce Cart settings'
  mapping:
    cart_page:
      type: mapping
      label: 'Cart page settings'
      mapping:
        view:
          type: string
          label: 'Shopping cart view'
